name: PR Test
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
permissions:
  id-token: write
  contents: write
  checks: write
  pull-requests: write
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: jwalton/gh-find-current-pr@89ee5799558265a1e0e31fab792ebb4ee91c016b
        id: findPr

      - name: Setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: '24.12.0'
          registry-url: https://npm.pkg.github.com/

      - name: Install and Build ğŸ”§
        run: |
          npm ci
          npm run build

      - name: Run Tests
        run: npm run pr:test

      - name: Test Report
        uses: dorny/test-reporter@ee446707ff3bdadb3c039ff1af4286a09acb79c6 # v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: JEST Tests # Name of the check run which will be created
          path: junit.xml # Path to test results
          reporter: jest-junit # Format of test results

      - name: Publish Coverage Report
        uses: ArtiomTr/jest-coverage-report-action@82bc34a0347019ba8f6d2808cd96cec42ef9620e
        id: coverage
        with:
          working-directory: ./
          coverage-file: report.json
          base-coverage-file: report.json
          output: report-markdown
          prnumber: ${{ steps.findPr.outputs.number }}

      - name: Pull Request Comment
        uses: marocchino/sticky-pull-request-comment@5060d4700a91de252c87eeddd2da026382d9298a
        with:
          # pass output from the previous step by id.
          message: ${{ steps.coverage.outputs.report }}
