name: Release
concurrency: main
on:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write # for changesets/action to push to the repo
      pull-requests: write # for changesets/action to create PRs
      packages: write # for publishing to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          # This makes action fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Setup üî®
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: '20.14.0'
          registry-url: https://npm.pkg.github.com/
          scope: '@Deloitte'
      - name: Install
        run: |
          npm ci
          git config --global user.name "GitHub CD bot"
          git config --global user.email "github-cd-bot@github.com"
      - name: Build
        run: |
          npm run build --if-present
      - name: PR and/or Publish
        id: changesets
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          publish: |
            npx changeset publish
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload dist/beacon.js asset
        if: steps.changesets.outputs.published == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.changesets.outputs.upload_url }}
          asset_path: ./dist/beacon.js
          asset_name: beacon.js
          asset_content_type: application/javascript
